### PR TITLE
added dynamic checking of supported platforms

### PR DESCRIPTION
**Pull request by Cvetomird91**
I've added a dynamic check for the supported platforms in TLDR. 

Please review and comment and let me know if you agree with those changes.

### CODE REVIEW

**Comment by YellowApple** [comment]
Temporarily postponing this until offline caching functionality is implemented (since that'll change the "ideal" way of going about this).  Leaving open until the effect of this PR is implemented (as a reminder to make sure that said functionality is present).

**Comment by Cvetomird91** [comment]
Can you please provide me with an update on the state of this PR? What is the state of the offline caching functionality feature as we speak? 

I would be glad to participate and improve my commit. :)

**Comment by YellowApple** [comment]
Sorry for the delay on this.  Can you rebase this PR on the latest master (if it ain't already)?  Once that's done, I'll go ahead and test/merge it.

**Comment by Cvetomird91** [comment]
Can you please provide me with information on the steps to perform this? I haven't rebased a PR that is behind the upstream with a few commits.

**Comment by YellowApple** [comment]
The general procedure is to checkout your branch, run `git rebase master`, and resolve any conflicts.  Is there a specific step you're stuck on?

I'd do it myself, but I don't believe myself to have commit access to your fork.

**Comment by Cvetomird91** [comment]
This is the output I'm getting:

> First, rewinding head to replay your work on top of it...
Applying: added dynamic checking of supported platforms
Using index info to reconstruct a base tree...
M	bin/tldrb
<stdin>:21: space before tab in indent.
  					"/contents/pages/"
<stdin>:36: new blank line at EOF.
+

> warning:

> 2 lines add whitespace errors.
>Falling back to patching base and 3-way merge...
>Auto-merging bin/tldrb
>CONFLICT (content): Merge conflict in bin/tldrb
>Failed to merge in the changes.
>Patch failed at 0001 added dynamic checking of supported platforms
>The copy of the patch that failed is found in:
>   /home/cvetomir/workspaces/tldrb/.git/rebase-apply/patch

> When  you have resolved this problem, run "git rebase --continue". If you prefer to skip this patch, run "git rebase --skip" instead. To check out the original branch and stop rebasing, run "git rebase --abort".

**Pull request closed without merging**
